[functions.trainer-create-athlete]
verify_jwt = true

[functions.auth-signup]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-create-membership-checkout]
verify_jwt = true

[functions.stripe-create-portal-session]
verify_jwt = true

[functions.stripe-create-membership-portal-session]
verify_jwt = true

[functions.planner-hub-api]
verify_jwt = false
