/*
  # Extend race_plans table for nutrition satellite payload

  ## Summary
  Adds all fields sent by the nutrition satellite's push-race-plan endpoint
  that are not yet present in the race_plans table. Also adds is_active flag
  for tracking which plan is currently active for a given athlete.

  ## New Columns
  - `is_active` - boolean flag for the athlete's currently active race plan
  - `race_date` - actual race date (may differ from scheduled_date)
  - `humidity_pct` - ambient humidity percentage
  - `altitude_m` - race altitude in meters
  - `intensity_percent` - target intensity as % of max
  - `intensity_zone` - training zone label (e.g. "Zone 3")
  - `pacing_recommendation` - free-text pacing advice
  - `carb_sources` - JSONB array of carbohydrate source objects
  - `carb_timing` - JSONB with carb timing breakdown by phase
  - `sweat_rate_l_per_hour` - athlete sweat rate
  - `projected_mass_loss_pct` - projected body mass loss during race
  - `caffeine_mg_per_kg` - caffeine dose relative to body weight
  - `caffeine_sources` - JSONB array of caffeine source objects
  - `caffeine_notes` - free-text caffeine strategy notes
  - `pre_comp_notes` - general pre-competition notes
  - `cho_loading_days` - number of carb-loading days before race
  - `pre_comp_days` - JSONB array of pre-competition day nutrition plans
  - `race_breakfast_timing` - hours before race start for breakfast
  - `race_breakfast_description` - text description of race breakfast
  - `race_breakfast_carbs_g` - carbs in race breakfast (grams)
  - `gi_training_weeks` - weeks of gut training completed
  - `gi_training_target_g_per_hour` - gut training target g carbs/hr
  - `gi_training_notes` - free-text gut training notes
  - `gi_sessions` - JSONB array of gut training session records
  - `risks` - JSONB array of identified risk objects
  - `athlete_notes` - JSONB array of athlete-specific notes/observations
  - `generated_at` - timestamp when the plan was generated by the satellite
  - `plan_version` - version string (e.g. "1.0")
*/

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'is_active') THEN
    ALTER TABLE race_plans ADD COLUMN is_active boolean DEFAULT false;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'race_date') THEN
    ALTER TABLE race_plans ADD COLUMN race_date date;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'humidity_pct') THEN
    ALTER TABLE race_plans ADD COLUMN humidity_pct numeric;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'altitude_m') THEN
    ALTER TABLE race_plans ADD COLUMN altitude_m numeric;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'intensity_percent') THEN
    ALTER TABLE race_plans ADD COLUMN intensity_percent numeric;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'intensity_zone') THEN
    ALTER TABLE race_plans ADD COLUMN intensity_zone text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'pacing_recommendation') THEN
    ALTER TABLE race_plans ADD COLUMN pacing_recommendation text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'carb_sources') THEN
    ALTER TABLE race_plans ADD COLUMN carb_sources jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'carb_timing') THEN
    ALTER TABLE race_plans ADD COLUMN carb_timing jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'sweat_rate_l_per_hour') THEN
    ALTER TABLE race_plans ADD COLUMN sweat_rate_l_per_hour numeric;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'projected_mass_loss_pct') THEN
    ALTER TABLE race_plans ADD COLUMN projected_mass_loss_pct numeric;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'caffeine_mg_per_kg') THEN
    ALTER TABLE race_plans ADD COLUMN caffeine_mg_per_kg numeric;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'caffeine_sources') THEN
    ALTER TABLE race_plans ADD COLUMN caffeine_sources jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'caffeine_notes') THEN
    ALTER TABLE race_plans ADD COLUMN caffeine_notes text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'pre_comp_notes') THEN
    ALTER TABLE race_plans ADD COLUMN pre_comp_notes text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'cho_loading_days') THEN
    ALTER TABLE race_plans ADD COLUMN cho_loading_days integer;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'pre_comp_days') THEN
    ALTER TABLE race_plans ADD COLUMN pre_comp_days jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'race_breakfast_timing') THEN
    ALTER TABLE race_plans ADD COLUMN race_breakfast_timing numeric;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'race_breakfast_description') THEN
    ALTER TABLE race_plans ADD COLUMN race_breakfast_description text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'race_breakfast_carbs_g') THEN
    ALTER TABLE race_plans ADD COLUMN race_breakfast_carbs_g numeric;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'gi_training_weeks') THEN
    ALTER TABLE race_plans ADD COLUMN gi_training_weeks integer;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'gi_training_target_g_per_hour') THEN
    ALTER TABLE race_plans ADD COLUMN gi_training_target_g_per_hour integer;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'gi_training_notes') THEN
    ALTER TABLE race_plans ADD COLUMN gi_training_notes text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'gi_sessions') THEN
    ALTER TABLE race_plans ADD COLUMN gi_sessions jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'risks') THEN
    ALTER TABLE race_plans ADD COLUMN risks jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'athlete_notes') THEN
    ALTER TABLE race_plans ADD COLUMN athlete_notes jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'generated_at') THEN
    ALTER TABLE race_plans ADD COLUMN generated_at timestamptz;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'race_plans' AND column_name = 'plan_version') THEN
    ALTER TABLE race_plans ADD COLUMN plan_version text DEFAULT '1.0';
  END IF;
END $$;

-- Index to quickly find the active plan for an athlete
CREATE INDEX IF NOT EXISTS idx_race_plans_athlete_active ON race_plans (athlete_id, is_active) WHERE is_active = true;
